language: bash
services: docker

env:
  - VARIANT=php7.2/apache
  - VARIANT=php7.2/fpm
  - VARIANT=php7.2/fpm-alpine
  - VARIANT=php7.3/apache
  - VARIANT=php7.3/fpm
  - VARIANT=php7.3/fpm-alpine
  - VARIANT=php7.4/apache
  - VARIANT=php7.4/fpm
  - VARIANT=php7.4/fpm-alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VARIANT"
  - slash='/'; image="joomla:${VARIANT//$slash/-}"

script:
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
